### ISSUE TITLE
Project setup

### ISSUE THREAD

**Issue by przemekm1998** [przemekm1998/airbnb#1]
#### Description
Setup the project.

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [x] setup flask basic project structure
- [x] add project Dockerfile and docker-compose with services
- [x] add black and pre-commit hook
- [x] add Travis CI
